name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get install graphviz -y
        ls -la
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Check MD syntax
      run: |
        pymarkdown -d MD041,MD013,MD024 scan pages
        pymarkdown -d MD041,MD013,MD024 scan .
    - name: Publish MD files to the Confluence space
      env:
        LOGIN: ${{ secrets.ATLASSIAN_USERNAME }}
        PASSWORD: ${{ secrets.ATLASSIAN_API_TOKEN }}
      run: |
        for script in ./diagrams/*.py; do
          python3 "$script"
        done
        python3 ./publisher/main.py --login="$LOGIN" --password="$PASSWORD"
